---
title: "IMDB_Viz_R Report"
output: 
  html_document:
params:
  genre: "Drama"
  star: "Morgan Freeman"
  minRevenue: "$24M"
  year: !r c(1920, 2020)
  runtimes: !r c(70, 200)
---

**Selected Genre(s)**: `r params$genre`
**Selected Minimum Revenue**: `r params$minRevenue`
**Selected Year Range**: `r params$year`
**Selected Runtime Range**: `r params$runtimes`

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(shiny)
library(tidyverse)
library(shinyWidgets)
library(purrr)
library(here)

movies <- read.csv(here("data", "imdb_top_1000.csv"), stringsAsFactors = FALSE) %>%
  mutate(Runtime = as.numeric(gsub("([0-9]+).*$", "\\1", Runtime))) %>%
  mutate(Gross = as.numeric(gsub(",", "", Gross)) / 1000000)

plot_movies <- separate_rows(movies, Genre, sep = ",")
plot_movies$Genre <- trimws(plot_movies$Genre)
plot_movies$Series_Title <- trimws(plot_movies$Series_Title)

plot_data <- plot_movies %>%
  filter(Gross >= params$minRevenue,
         Released_Year >= params$year[1] & Released_Year <= params$year[2],
         Runtime >= params$runtimes[1] & Runtime <= params$runtimes[2],
         str_detect(Genre, paste(params$genre, collapse = "|")),
         Star1 %in% params$star | Star2 %in% params$star | Star3 %in% params$star | Star4 %in% params$star)


genre_data <- plot_movies %>%
  filter(str_detect(Genre, paste(params$genre, collapse = "|")))  %>%
  distinct(Series_Title, .keep_all = TRUE) %>%
  arrange(desc(IMDB_Rating)) %>%
            head(5)

```



```{r message=FALSE, warning=FALSE}
    
    ggplot(
      genre_data, 
      aes(x = IMDB_Rating, y = reorder(Series_Title, IMDB_Rating), fill = IMDB_Rating)) +
      geom_bar(stat = "identity") +
      geom_text(aes(label = Series_Title), hjust = 1.1, size = 7, face = "bold") +
      scale_fill_gradient(low = "lightyellow", high = "red") +
      theme(axis.text.y = element_blank()) +
      theme(
        plot.title = element_text(size = 20, face = "bold"),
        axis.title = element_text(size = 15, face = "bold"),
        axis.text = element_text(size = 12, face = "bold")
      ) +
      guides(fill = FALSE)+
      coord_cartesian(xlim = c(7, 9.5)) +
      labs(x = "Rating", y = "") +
      ggtitle(paste("Top 5 Movies by Rating in the selected Genre"))

```



```{r message=FALSE, warning=FALSE}

    ggplot(
      plot_data,
      aes(x = IMDB_Rating, y = Genre, fill = Genre)
    ) +
      geom_boxplot() +
      theme(
        plot.title = element_text(size = 20, face = "bold"),
        axis.title = element_text(size = 15, face = "bold"),
        axis.text = element_text(size = 12, face = "bold")
      ) +
      labs(x = "IMDB Rating", y = "Selected Genres") +
      ggtitle("Distribution of IMDB Ratings by Genre") +
      scale_x_continuous(breaks = seq(7.0, 10.0, by = 0.2))

```



```{r message=FALSE, warning=FALSE}

    ggplot(
      plot_data,
      aes(x = Runtime, y = Genre, fill = Genre)
    ) +
      geom_boxplot() +
      theme(
        plot.title = element_text(size = 20, face = "bold"),
        axis.title = element_text(size = 15, face = "bold"),
        axis.text = element_text(size = 12, face = "bold")
      ) +
      labs(x = "Movie Runtime(mins)", y = "Selected Genres") +
      ggtitle("Distribution of Runtimes by Genre") +
      scale_x_continuous(breaks = seq(40, 321, by = 10))

```



```{r message=FALSE, warning=FALSE}

    ggplot(
      plot_data,
      aes(y = Genre, fill = Genre)
    ) +
      geom_bar() +
      theme(
        plot.title = element_text(size = 20, face = "bold"),
        axis.title = element_text(size = 15, face = "bold"),
        axis.text = element_text(size = 12, face = "bold")
      ) +
      labs(x = "Number of movies", y = "Selected Genres") +
      ggtitle("Number of Movies by Genres")

```


